Repository anitab-org/mentorship-android, pull requests merged in 2018-11, with the labels that each got.

#74 UI Test Added for SignUpActivity
  app/build.gradle
  app/src/androidTest/java/org/systers/mentorship/SignUpActivityTest.kt
  app/src/main/res/layout/activity_login.xml
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: Type: Testing

#86 Refactor update profile fragment.
  app/src/main/java/org/systers/mentorship/remote/ApiManager.kt
  app/src/main/java/org/systers/mentorship/remote/datamanager/AuthDataManager.kt
  app/src/main/java/org/systers/mentorship/remote/datamanager/RelationDataManager.kt
  app/src/main/java/org/systers/mentorship/remote/datamanager/UserDataManager.kt
  app/src/main/java/org/systers/mentorship/remote/responses/CustomResponse.kt
  app/src/main/java/org/systers/mentorship/remote/services/AuthService.kt
  app/src/main/java/org/systers/mentorship/remote/services/RelationService.kt
  app/src/main/java/org/systers/mentorship/remote/services/UserService.kt
  app/src/main/java/org/systers/mentorship/utils/Constants.kt
  app/src/main/java/org/systers/mentorship/view/activities/MainActivity.kt
  app/src/main/java/org/systers/mentorship/view/activities/MemberProfileActivity.kt
  app/src/main/java/org/systers/mentorship/view/activities/RequestDetailActivity.kt
  app/src/main/java/org/systers/mentorship/view/activities/SendRequestActivity.kt
  app/src/main/java/org/systers/mentorship/view/adapters/RequestsPagerAdapter.kt
  app/src/main/java/org/systers/mentorship/view/fragments/BaseFragment.kt
  app/src/main/java/org/systers/mentorship/view/fragments/EditProfileFragment.kt
  app/src/main/java/org/systers/mentorship/view/fragments/MembersFragment.kt
  app/src/main/java/org/systers/mentorship/view/fragments/ProfileFragment.kt
  app/src/main/java/org/systers/mentorship/view/fragments/RelationFragment.kt
  app/src/main/java/org/systers/mentorship/view/fragments/RequestPagerFragment.kt
  app/src/main/java/org/systers/mentorship/view/fragments/RequestsFragment.kt
  app/src/main/java/org/systers/mentorship/viewmodels/MemberProfileViewModel.kt
  app/src/main/java/org/systers/mentorship/viewmodels/ProfileViewModel.kt
  app/src/main/java/org/systers/mentorship/viewmodels/RelationViewModel.kt
  app/src/main/java/org/systers/mentorship/viewmodels/RequestDetailViewModel.kt
  app/src/main/java/org/systers/mentorship/viewmodels/RequestsViewModel.kt
  app/src/main/java/org/systers/mentorship/viewmodels/SendRequestViewModel.kt
  app/src/main/java/org/systers/mentorship/viewmodels/SignUpViewModel.kt
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: Type: Enhancement

#93 chore: Update kotlin to 1.3.0
  buildSrc/src/main/java/Dependencies.kt
Labels: Type: Maintenance

#80 SendRequestActivity null check fixed
  app/src/main/java/org/systers/mentorship/view/activities/SendRequestActivity.kt
  app/src/main/res/values/strings.xml
Labels: Type: Bug

#97 fix: User can update mentor/mentee availability
  app/src/main/java/org/systers/mentorship/view/fragments/EditProfileFragment.kt
Labels: Type: Bug

#104 Implemented Settings screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/systers/mentorship/view/activities/MainActivity.kt
  app/src/main/java/org/systers/mentorship/view/activities/SettingsActivity.kt
  app/src/main/res/drawable/ic_settings_white_24dp.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values/strings.xml
Labels: Type: Enhancement
