Repository anitab-org/mentorship-android, pull requests merged in 2018-10, with the labels that each got.

#73 Changed date format to Calendar in Send Request
  app/src/main/java/org/systers/mentorship/view/activities/SendRequestActivity.kt
  app/src/main/res/drawable/ic_date_range_black_24dp.xml
  app/src/main/res/layout/activity_send_request.xml
Labels: Type: Enhancement

#78 Fixes fragment reloading when app goes in landscape mode.
  app/src/main/java/org/systers/mentorship/view/activities/MainActivity.kt
Labels: Type: Bug

#83 Screen update when the relation is cancelled
  app/src/main/java/org/systers/mentorship/view/fragments/RelationFragment.kt
Labels: Review Requested, Type: Bug
