Repository anitab-org/mentorship-android, pull requests merged in 2020-06, with the labels that each got.

#706 Fix: #679 Required error not visible in Confirm password field
  app/src/main/java/org/systers/mentorship/view/activities/SignUpActivity.kt
Labels: Category: Coding, Status: Ready to Merge, Type: Bug

#703 FIX: App crashes when anything is typed in the search bar in Members Fragment
  app/src/main/java/org/systers/mentorship/view/fragments/MembersFragment.kt
Labels: Category: Coding, Help Wanted, Status: Needs Testing, Type: Bug

#629 fix: Settings screen list items
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/styles.xml
Labels: Category: Coding, Status: Ready to Merge, Type: Bug

#698 fix :Save in (Profile) when no change detected
  app/src/main/java/org/systers/mentorship/view/fragments/EditProfileFragment.kt
Labels: Category: Coding, Category: User Interface, Status: Ready to Merge, Type: Bug

#721 feat: back button takes to LoginActivity from SignUpActivity
  app/src/main/java/org/systers/mentorship/view/activities/LoginActivity.kt
Labels: Status: Ready to Merge, Type: Bug

#725 fix: Bottom Navigation Tab Reselected Bug
  app/src/main/java/org/systers/mentorship/view/activities/MainActivity.kt
Labels: Category: Coding, Status: Ready to Merge, Type: Bug

#722 Fix#649 Zulip and GitHub buttons in about acivity
  app/src/main/res/drawable/ic_code_of_conduct.xml
  app/src/main/res/drawable/ic_github.xml
  app/src/main/res/drawable/ic_privacy.xml
  app/src/main/res/drawable/ic_terms_and_condition.xml
  app/src/main/res/drawable/ic_web.xml
  app/src/main/res/drawable/ic_zulip.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/values/dimens.xml
Labels: Category: User Interface, Status: Ready to Merge, Type: Bug

#723 Fixes ScrollView Bug in FeedBack Page
  app/src/main/res/layout/activity_feedback.xml
Labels: Category: User Interface, Status: Needs Review, Type: Bug

#731 Update mentorship_system_logo.png
  app/src/main/res/drawable-v24/mentorship_system_logo.png
Labels: Category: User Interface, Status: Ready to Merge, Type: Bug
