Repository anitab-org/mentorship-android, pull requests merged in 2020-07, with the labels that each got.

#531 feat: add intro slider when signing in
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/systers/mentorship/dsl/Context.kt
  app/src/main/java/org/systers/mentorship/view/activities/IntroActivity.kt
  app/src/main/java/org/systers/mentorship/view/activities/SplashScreenActivity.kt
  app/src/main/res/drawable/ic_undraw_a_day_off.xml
  app/src/main/res/drawable/ic_undraw_people.xml
  app/src/main/res/drawable/ic_undraw_proud_self.xml
  app/src/main/res/drawable/ic_undraw_shared_workspace.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/values/strings.xml
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: Category: Coding, Category: User Interface, Status: Ready to Merge, Type: Enhancement

#713 feat: Order mentorship requests in a descending order based on the creation date
  app/src/main/java/org/systers/mentorship/viewmodels/RequestsViewModel.kt
Labels: Category: Coding, Help Wanted, Status: Needs Testing, Type: Enhancement

#712 pagination added to members screen
  app/src/main/java/org/systers/mentorship/remote/datamanager/UserDataManager.kt
  app/src/main/java/org/systers/mentorship/remote/requests/PaginationRequest.kt
  app/src/main/java/org/systers/mentorship/remote/services/UserService.kt
  app/src/main/java/org/systers/mentorship/utils/Constants.kt
  app/src/main/java/org/systers/mentorship/utils/EndlessRecyclerScrollListener.kt
  app/src/main/java/org/systers/mentorship/utils/UsersDiffCallback.kt
  app/src/main/java/org/systers/mentorship/view/adapters/MembersAdapter.kt
  app/src/main/java/org/systers/mentorship/view/fragments/MembersFragment.kt
  app/src/main/java/org/systers/mentorship/viewmodels/MembersViewModel.kt
  app/src/main/res/layout/fragment_members.xml
  app/src/main/res/values/dimens.xml
Labels: Category: Coding, Status: Ready to Merge, Type: Enhancement

#728 fix: tasks fragment margins
  app/src/main/res/layout/fragment_mentorship_tasks.xml
Labels: Category: User Interface, Status: Ready to Merge, Type: Bug

#717 Update README with app features
  README.md
Labels: Category: Documentation/Training, Status: Ready to Merge
