Repository anitab-org/mentorship-android, pull requests merged in 2020-04, with the labels that each got.

#423 Add password security check
  app/src/androidTest/java/org/systers/mentorship/SignUpActivityTest.kt
  app/src/main/java/org/systers/mentorship/utils/Extensions.kt
  app/src/main/java/org/systers/mentorship/view/activities/SignUpActivity.kt
  app/src/main/java/org/systers/mentorship/view/fragments/ChangePasswordFragment.kt
  app/src/main/res/values/strings.xml
Labels: Review Requested

#643 Fixes #642: Replace all reference of Slack with Zulip in README.md
  README.md
Labels: Category: Documentation/Training, Type: Maintenance

#690 Fix: Ambiguous subscript of empty username/email fixed
  app/src/main/res/values/strings.xml
Labels: Category: User Interface, Type: Enhancement

#617 Fixed the alignment
  app/src/main/res/layout/activity_sign_up.xml
Labels: Category: User Interface, Needs Testing

#686 fix : signUp with mentee/mentor unchecked
  app/src/main/java/org/systers/mentorship/view/activities/SignUpActivity.kt
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: Needs Testing, Review Requested
