Repository anitab-org/mentorship-android, pull requests merged in 2020-05, with the labels that each got.

#630 refactor: Put all hardcoded strings from FeedbackActivity on strings.xml
  app/src/main/java/org/systers/mentorship/view/activities/FeedbackActivity.kt
  app/src/main/res/values/strings.xml
Labels: Category: Coding, Type: Maintenance

#687 Fix mismatch bug issue 614
  app/src/main/java/org/systers/mentorship/view/activities/MemberProfileActivity.kt
Labels: Status: Ready to Merge, Type: Bug

#705 FIX: App crashed on clicking edit profile button before the user data was loaded.
  app/src/main/java/org/systers/mentorship/view/fragments/ProfileFragment.kt
Labels: Category: Coding, Status: Ready to Merge, Type: Bug

#634 Fixes issue #574. changed the background colour of activity_splash_screen to white
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_splash_screen.xml
Labels: Category: Coding, Category: Quality Assurance, Category: User Interface, Status: Ready to Merge
