Repository anitab-org/mentorship-android, pull requests merged in 2020-11, with the labels that each got.

#991 Fix : Fixed feedback screen validation error #987
  app/src/main/java/org/systers/mentorship/view/activities/FeedbackActivity.kt
Labels: Status: Ready to Merge

#834 test: Added Logout Test.
  app/src/androidTest/java/org/systers/mentorship/view/fragments/LogoutTest.kt
Labels: Status: Ready to Merge

#814 style: Change App name to Mentorship System
  app/src/main/res/values/strings.xml
Labels: Open Source Hack, Status: Ready to Merge

#836 test: Added Test for Change Password Fragment - Scenario (b)
  app/src/androidTest/java/org/systers/mentorship/view/fragments/ChangePasswordFragmentTest.kt
Labels: Open Source Hack, Status: Needs Review

#1032 Removed redundant app namespace - fix for #1008
  app/src/main/res/layout/activity_login.xml
Labels: Status: Ready to Merge
