Repository anitab-org/mentorship-android, pull requests merged in 2021-02, with the labels that each got.

#1068 docs : Comment out descriptions in Issue templates and PR template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Status: Needs Review

#1060 Write "Request Detail" Screen Espresso test (a)
  app/src/androidTest/java/org/systers/mentorship/RequestDetailActivityTestA.kt
Labels: Status: Ready to Merge

#1059 Write "Request Detail" Screen Espresso test (b)
  app/src/androidTest/java/org/systers/mentorship/RequestDetailTestB.kt
Labels: Status: Ready to Merge

#954 fix: Adding runtime checks to signup page for the email and confirm password
  app/src/main/java/org/systers/mentorship/view/activities/SignUpActivity.kt
Labels: Status: Ready to Merge

#885 docs: updated the code of conduct
  docs/CODE_OF_CONDUCT.md
Labels: Status: Ready to Merge

#1078 docs: Updated Code of Conduct
  docs/CODE_OF_CONDUCT.md
Labels: Status: Needs Review

#1076 Fix : Fixed hardcoded strings in SignUp activity
  app/src/main/java/org/systers/mentorship/view/activities/SignUpActivity.kt
Labels: Status: Ready to Merge

#1082 resizing image and table guidelines added
  .github/CONTRIBUTING.md
Labels: Status: Ready to Merge

#1084 Fix#1058 Updated .travis.yml
  .travis.yml
Labels: Status: Ready to Merge

#906 docs: Create tasks for a relation and complete the task
  docs/manual_tests/create_tasks_in_relation_and_complete_task.md
Labels: Status: Needs Review

#1030 Fix login activity tests
  app/src/androidTest/java/org/systers/mentorship/LoginActivityTest.kt
Labels: Status: Needs Testing

#984 Fix: Login bug
  app/src/main/java/org/systers/mentorship/remote/TokenAuthenticator.kt
Labels: Status: Ready to Merge
